apiVersion: v1
kind: Service
metadata:
  name: blog-mongodb
  namespace: blog-namespace
spec:
  selector:
    app: blog-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP