apiVersion: v1
kind: Service
metadata:
  name: blog-app
  namespace: blog-namespace
spec:
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort